In [26]:
import gym
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import deque

In [188]:
class approximator(nn.Module):
    def __init__(self):
        super().__init__()
        self.act1 = F.leaky_relu
        self.layer1 = nn.Linear(129, 32) # hidden layer 1
        self.act2 = F.leaky_relu
        self.layer2 = nn.Linear(32, 32)  # hidden layer 2
        self.layer3 = nn.Linear(32, 1)   # output layer
        self.loss = F.mse_loss           # loss function
    
    def forward(self, inputs):
        out = self.act1(self.layer1(inputs))
        out = self.act2(self.layer2(out))
        out = self.layer3(out)
        return out
    
    def train(self, inputs, targets): 
        self.opt = torch.optim.SGD(self.parameters(), lr = 1e-8)
        num_epochs = 30
        for epoch in range(num_epochs):
            out = self(inputs)
            error = self.loss(out, targets)
            error.backward()
            self.opt.step()
            self.opt.zero_grad()      

In [27]:
class Agent:
    def __init__(self, env):
        self.experience = deque(10_000)
        
        self.q_values = approximator()
        self.q_values_ = approximator()
    
        self.env = env
        self.actions = [action for action in range(env.env.action_space.n)]
        self.epsilon = 0.1 / len(self.actions)
        self.gamma = 1
        
    def select_action(self, state):
        action = -1
        
        if (np.random.random() < self.epsilon):
            action = np.random.choice(self.actions)
            return action
        
        values = []
        for action in self.actions:
            inp = torch.tensor(np.append(state, [action])).float().reshape(1, -1)
            value = float(self.q_values(inp))
            values.append((value, action))
        values.sort(reverse = True)
        return values[0][1]
    
    def take_action(self, state):
        action = self.select_action(state)
        next_state, reward, done = self.env.step(action)
        
        
        

In [6]:
for i in range(10):
    state = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = np.random.choice([0, 1, 2, 3, 4, 5])
        n_state, reward, done, info = env.step(action)
        score += reward
    print(f'Episode:{i} Score:{score}')
env.close()

Episode:0 Score:100.0
Episode:1 Score:155.0
Episode:2 Score:370.0
Episode:3 Score:135.0
Episode:4 Score:125.0
Episode:5 Score:255.0
Episode:6 Score:70.0
Episode:7 Score:90.0
Episode:8 Score:45.0
Episode:9 Score:105.0


In [18]:
env = gym.make('SpaceInvaders-ram-v0')

In [19]:
env.action_space

Discrete(6)

In [25]:
env.reset()

array([  0,   7,   0,  68, 241, 162,  34, 183,  68,  13, 124, 255, 255,
        50, 255, 255,   0,  36,  63,  63,  63,  63,  63,  63,  82,   0,
        23,  43,  35, 117, 180,   0,  36,  63,  63,  63,  63,  63,  63,
       110,   0,  23,   1,  60, 126, 126, 126, 126, 255, 255, 255, 195,
        60, 126, 126, 126, 126, 255, 255, 255, 195,  60, 126, 126, 126,
       126, 255, 255, 255, 195,   0,   0,  48,   3, 129,   0,   0,   0,
         0,   0,   0, 246, 246,  63,  63, 246, 246,  63,  63,   0,  21,
        24,   0,  52,  82, 196, 246,  20,   7,   0, 226,   0,   0,   0,
         0,   0,  21,  63,   0, 128, 171,   0, 255,   0, 189,   0,   0,
         0,   0,   0,  99, 255,   0,   0, 235, 254, 192, 242], dtype=uint8)

In [160]:
a = approximator()

In [162]:
inp = torch.tensor(np.array([[i for i in range(129)], [-i for i in range(129)]])).float()

In [163]:
tar = torch.tensor(np.array([[8256], [-8256]])).float()

In [186]:
for i in range(10):
    a.train(inp, tar)

In [187]:
a(inp)

tensor([[ 8256.],
        [-8256.]], grad_fn=<AddmmBackward>)

In [164]:
inp

tensor([[   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
           10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,   19.,
           20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,   28.,   29.,
           30.,   31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.,
           40.,   41.,   42.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,
           50.,   51.,   52.,   53.,   54.,   55.,   56.,   57.,   58.,   59.,
           60.,   61.,   62.,   63.,   64.,   65.,   66.,   67.,   68.,   69.,
           70.,   71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,
           80.,   81.,   82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,
           90.,   91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,
          100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,  109.,
          110.,  111.,  112.,  113.,  114.,  115.,  116.,  117.,  118.,  119.,
          120.,  121.,  122.,  123.,  124.,  125.,  

In [165]:
tar

tensor([[ 8256.],
        [-8256.]])

In [200]:
x=env.action_space

In [204]:
x.n

6

In [209]:
x = np.array([1, 2])

In [211]:
np.append(x, [3])

array([1, 2, 3])

In [213]:
x=torch.tensor([[1]])

In [215]:
x

tensor([[1]])

In [223]:
float(x)

1.0

In [224]:
env.step?